version: "3.6"
services:
  my-mysql-master1: 
    build: .
    image: my-mysql-master:8.0.2
    container_name: my-mysql-master1
    #restart: unless-stopped
    ports: 
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    volumes: 
      - "./master_home/data:/var/lib/mysql"
      - "./master_home/config/my.cnf:/etc/mysql/my.cnf"
      - "../hosts:/etc/hosts"
    entrypoint: 
      - docker-entrypoint.sh
    command: 
      - mysqld
    networks:
      default:
       ipv4_address: 172.24.0.101
networks:
  default:
    external:
      name: my-network