version: "3.6"
services:
  my-nexus:
    build: .
    image: sonatype/nexus3:3.21.1
    container_name: my-nexus
    ports: 
      - "8081:8081"
    volumes: 
      - "./nexus_home/nexus-data:/nexus-data"
      - "../hosts:/etc/hosts"
    networks:
      default:
       ipv4_address: 172.24.0.90
networks:
  default:
    external:
      name: my-network


