#https://github.com/nginxinc/docker-nginx/blob/master/stable/buster/Dockerfile
FROM fauria/vsftpd
ADD Centos-7.repo /etc/yum.repos.d/CentOS-Base.repo

RUN yum install -y net-tools 
RUN yum install -y iputils




