version: "3.6"
services:
  my-maven:
    build: .
    image: maven:3-jdk-8
    container_name: my-maven
    stdin_open: true
    tty: true
    privileged: true
    working_dir: /home/myuser/projects
    volumes: 
      - "./mvn_home/settings.xml:/usr/share/maven/conf/settings.xml"
      - "./mvn_home/projects/:/home/myuser/projects/"
      - "./mvn_home/repository/:/root/.m2/repository/"       
      - "../hosts:/etc/hosts"
    
    command:
      - /bin/bash
      - -c
      - | 
        sh
    networks:
      default:
       ipv4_address: 172.24.0.66
networks:
  default:
    external:
      name: my-network
