version: "3.6"
services:
  my-mysql-slave1: 
    build: .
    image: my-mysql-slave:8.0.2
    container_name: my-mysql-slave1
    #restart: unless-stopped
    ports: 
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    volumes: 
      - "./slave_home/data:/var/lib/mysql"
      - "./slave_home/config/my.cnf:/etc/mysql/my.cnf"
      - "../hosts:/etc/hosts"
    entrypoint: 
      - docker-entrypoint.sh
    command: 
      - mysqld
    networks:
      default:
       ipv4_address: 172.24.0.201
networks:
  default:
    external:
      name: my-network