version: "3.6"
services:
  my-gitlab:
    build: . 
    image: gitlab/gitlab-ce:12.8.6-ce.0
    container_name: my-gitlab
    restart: unless-stopped
    hostname: 'my-gitlab'
    environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://my-gitlab:880'
          gitlab_rails['time_zone'] = 'Asia/Shanghai'
          # 需要配置到 gitlab.rb 中的配置可以在这里配置，每个配置一行，注意缩进。
          # 比如下面的电子邮件的配置：
          # gitlab_rails['smtp_enable'] = true
          # gitlab_rails['smtp_address'] = "smtp.exmail.qq.com"
          # gitlab_rails['smtp_port'] = 465
          # gitlab_rails['smtp_user_name'] = "xxxx@xx.com"
          # gitlab_rails['smtp_password'] = "password"
          # gitlab_rails['smtp_authentication'] = "login"
          # gitlab_rails['smtp_enable_starttls_auto'] = true
          # gitlab_rails['smtp_tls'] = true
          # gitlab_rails['gitlab_email_from'] = 'xxxx@xx.com'
    ports: 
      - "222:22"
      - "4443:443"
      - "880:880"
    volumes: 
      - "./gitlab_home/etc:/etc/gitlab"
      - "./gitlab_home/log:/var/log/gitlab"
      - "./gitlab_home/var:/var/opt/gitlab"
      - "../hosts:/etc/hosts"
    networks:
      default:
       ipv4_address: 172.24.0.87
networks:
  default:
    external:
      name: my-network

