#centos
FROM nacos/nacos-server:1.1.4
#RUN yum install -y wget
#RUN wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo
ADD Centos-7.repo /etc/yum.repos.d/CentOS-Base.repo

RUN yum install -y net-tools 
RUN yum install -y iputils





