version: "3.6"
services:
  my-mysql:
    build: .
    image: daocloud.io/library/mysql:8.0.2
    container_name: my-mysql
    restart: unless-stopped
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    volumes: 
      - "./mysql_home/data:/var/lib/mysql"
      - "./mysql_home/config:/etc/mysql/conf.d"
      - "../hosts:/etc/hosts"
    entrypoint: 
      - docker-entrypoint.sh
    command: 
      - mysqld
    networks:
      default:
       ipv4_address: 172.24.0.7
networks:
  default:
    external:
      name: my-network