version: "3.6"
services:
  my-logstash:
    build: . 
    image: logstash:6.8.8
    container_name: my-logstash
    restart: unless-stopped
    hostname: 'my-logstash'

    ports: 
      - "5044:5044"
      - "9600:9600"

    volumes: 
      - "./log_home/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
      - "./log_home/config/logstash.yml:/usr/share/logstash/config/logstash.yml"
      - "../hosts:/etc/hosts"
    networks:
      default:
       ipv4_address: 172.24.0.76
networks:
  default:
    external:
      name: my-network

